language: none

services:
    - docker

build:
    pre_ci: 
        - docker build -t currobeltran/f1-predictor .

    pre_ci_boot:
        image_name: currobeltran/f1-predictor
        pull: true
        options: "-v `pwd`:/test"