language: none

services:
    - docker

build:
    pre_ci: 
        - docker build -t currobeltran/f1-predictor:lastest .

    pre_ci_boot:
        - image_name: currobeltran/f1-predictor
        - image_tag: lastest
        - pull: true
        - options: "-v `pwd`:/test"
