name: Heroku

on:
    push:
        branches:
            master

jobs:
    push:
        runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.8.9
          with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: "f1-predictor-iv"
              heroku_email: "currob1999@gmail.com"