name: Tests

on:
    workflow_run:
        workflows: "Docker"
        types:
            - completed
    
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Test contenedor de DockerHub
              run: make travis